language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
    - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install -r requirements-py3.txt; else pip install -r requirements-py2.txt; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install ordereddict>=1.1 unittest2==0.5.1; fi
# command to run tests
script: nosetests tests
